services:
  # Web service
  - type: web
    name: flask-shop
    runtime: python
    buildCommand: |
      echo "=== Python version check ==="
      python --version
      python3 --version
      which python
      which python3
      echo "=== Installing with legacy SQLAlchemy ==="
      pip install --upgrade pip
      pip install -r requirements_legacy.txt
      echo "=== Skipping DB init due to compatibility issues ==="
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app --workers 1 --timeout 300 --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://ittoken_db_user:Xm98VVSZv7cMJkopkdWRkgvZzC7Aly42@dpg-d0visga4d50c73ekmu4g-a.frankfurt-postgres.render.com/ittoken_db
      - key: DB_SCHEMA
        value: AndriIT
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  # PostgreSQL database
  - name: flask-shop-db
    databaseName: AndriIT
    user: AndriIT
    plan: free
