services:
  # Web service using full Flask Shop app from the flask_shop directory
  - type: web
    name: flask-shop
    runtime: python
    rootDir: flask_shop
    buildCommand: |
      echo "=== PYTHON VERSION CHECK ==="
      python --version
      echo "=== INSTALLING FULL APPLICATION DEPENDENCIES ==="
      pip install --upgrade pip
      # Use SQLAlchemy 1.4 which is more compatible with Python 3.13
      pip install -r requirements.txt
      pip uninstall -y sqlalchemy
      pip install sqlalchemy==1.4.53
      echo "=== INSTALLATION COMPLETE ==="
      pip list
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app --workers 1 --timeout 300
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://ittoken_db_user:Xm98VVSZv7cMJkopkdWRkgvZzC7Aly42@dpg-d0visga4d50c73ekmu4g-a.frankfurt-postgres.render.com/ittoken_db
      - key: DB_SCHEMA
        value: AndriIT
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  # PostgreSQL database
  - name: flask-shop-db
    databaseName: AndriIT
    user: AndriIT
    plan: free
