services:
  # Web service - Pure Python version (no Docker, no SQLAlchemy)
  - type: web
    name: flask-shop
    runtime: python
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: gunicorn app_direct:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  # PostgreSQL database
  - name: flask-shop-db
    databaseName: AndriIT
    user: AndriIT
    plan: free