services:
  # Web service using direct Flask Shop app without SQLAlchemy (compatible with Python 3.13)
  - type: web
    name: flask-shop
    runtime: python
    buildCommand: |
      echo "=== PYTHON VERSION CHECK ==="
      python --version
      echo "=== INSTALLING MINIMAL DEPENDENCIES ==="
      pip install --upgrade pip
      pip install Flask==3.0.0 gunicorn==21.2.0 python-dotenv==1.0.0 Jinja2==3.1.2 MarkupSafe==2.1.3 itsdangerous==2.1.2 Werkzeug==3.0.0
      echo "=== INSTALLATION COMPLETE ==="
      pip list
    startCommand: gunicorn --bind 0.0.0.0:$PORT direct_app:app --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://ittoken_db_user:Xm98VVSZv7cMJkopkdWRkgvZzC7Aly42@dpg-d0visga4d50c73ekmu4g-a.frankfurt-postgres.render.com/ittoken_db
      - key: DB_SCHEMA
        value: AndriIT
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

databases:
  # PostgreSQL database
  - name: flask-shop-db
    databaseName: AndriIT
    user: AndriIT
    plan: free
